# The CIFAR-10 dataset consists of 60000 32x32 colour images in 10 classes,
# with 6000 images per class. There are 50000 training images and 10000 test images.
n_step: 1000
min_b: 0.0001
max_b: 0.02
num_class: 10
time_emb_dim: 100
batch_size: 128
n_epoch: 20
lr: 0.001
device: cpu
model_path: ../00_assets/ddpm_model_with_class.pth